version: "3"

networks:
  proxy:
    external: true

services:
  miniflux:
    image: miniflux/miniflux:latest
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${HOST}
      - DATABASE_URL=postgres://miniflux:miniflux@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    networks:
      - default
      - proxy
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=miniflux
      - POSTGRES_DB=miniflux
    volumes:
      - ./data/db:/var/lib/postgresql/data
