version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - ${DNS_PORT}:53/tcp
      - ${DNS_PORT}:53/udp
      - ${WEB_PORT}:80
    environment:
      TZ: Europe/Berlin
      WEBPASSWORD: ${PASSWORD}
    volumes:
      - ./data/pihole-config:/etc/pihole
      - ./data/pihole-dns:/etc/dnsmasq.d
