version: '2'

networks:
  proxy:
    external: true

services:
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    links:
      - db
    volumes:
      - ./data/nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${HOST}
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - default
      - proxy

  db:
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
