version: "3"

services:
  adguard:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    ports:
      - ${DNS_PORT}:53/tcp
      - ${DNS_PORT}:53/udp
      - ${WEB_PORT}:80
      - ${SETUP_PORT}:3000
    volumes:
      - ./data/adguard-work:/opt/adguardhome/work
      - ./data/adguard-config:/opt/adguardhome/conf
