version: "3"

networks:
  proxy:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_HOST=${HOST}
    volumes:
      - ./data/uptime-kuma:/app/data
    networks:
      - default
      - proxy
