version: "3"

networks:
  proxy:
    external: true

services:
  paper:
    build: .
    restart: unless-stopped
    container_name: paper
    stdin_open: true
    tty: true
    environment:
      - VIRTUAL_HOST=${DYNMAP_HOST}
      - VIRTUAL_PORT=8123
      - LETSENCRYPT_HOST=${DYNMAP_HOST}
    volumes:
      - ./data/paper:/paper/
    ports:
      - 25565:25565
    networks:
      - default
      - proxy
